version: "2.4"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../test/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
    environment:
      DEBUG: 0
      SERVICES: s3,sqs,lambda
      SQS_ENDPOINT_STRATEGY: off