version: '2.4'

services:

  pipeline-restoration:
    build:
      context: ../
      target: test
      args:
        - GITHUB_TOKEN
    volumes:
      - $PWD/coverage:/opt/app/coverage:Z
    env_file: ../env/test.env
    command: sh -c 'npm run test:ci'
